# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_import: error
    dead_code: error
    avoid_print: error
    always_use_package_imports: error
    prefer_final_locals: error
    unnecessary_late: error
    use_build_context_synchronously: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    - always_use_package_imports
    - prefer_final_locals
    - unnecessary_late
    - avoid_print
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_redundant_argument_values
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_in_for_each
    - sort_child_properties_last
    - sort_constructors_first
    - unnecessary_null_checks
    - unnecessary_this
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_named_constants
    - use_super_parameters
